---
- name: Cronjob
  hosts: noncluster
  become: true
  tasks:
    - name: Add cronjob to reboot
      ansible.builtin.cron:
        name: "Nom de votre tâche cron"
        minute: "0"
        hour: "1"
        day: "*"
        month: "*"
        weekday: "*"
        user: root
        job: "test -f /var/run/reboot-required && /bin/systemctl reboot"
