---
- name: Reboot cluster controlplane staggered
  hosts: controlplane
  become: true
  vars_files:
    - "env_vars/k3s.yml"
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        test_command: kubectl get nodes

- name: Reboot cluster dataplane staggered
  hosts: dataplane
  become: true
  vars_files:
    - "env_vars/k3s.yml"
  gather_facts: true
  serial: 1
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
