---
- name: Kubernetes
  hosts: belt
  become: true
  vars_files:
    - "env_vars/kubernetes.yml"
  pre_tasks:
    - name: Create directory kubernetes
      ansible.builtin.file:
        path: /etc/kubernetes
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: kubernetes_role == "control_plane"

    - name: Copy audit policy
      ansible.builtin.template:
        src: "kubernetes/audit-policy.yaml"
        dest: "/etc/kubernetes/audit-policy.yaml"
        owner: "root"
        group: "root"
        mode: '0644'
      when: kubernetes_role == "control_plane"

    - name: Copy webhook config
      ansible.builtin.template:
        src: "kubernetes/webhook-config.yaml"
        dest: "/etc/kubernetes/webhook-config.yaml"
        owner: "root"
        group: "root"
        mode: '0644'
      when: kubernetes_role == "control_plane"

    - name: Download Kubernetes archive keyring
      ansible.builtin.command:
        cmd: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o {{ kubernetes_keyring_gpg_path }}

  roles:
    - geerlingguy.kubernetes


  post_tasks:
    - name: Copy custom resolv.conf for pods
      ansible.builtin.template:
        src: "kubernetes/kubelet-custom-resolv.conf"
        dest: "{{ resolvConf }}"
        owner: "root"
        group: "root"
        mode: '0644'
    - name: Copy extra args for kubelet
      ansible.builtin.template:
        src: "kubernetes/kubelet"
        dest: "/etc/default/kubelet"
        owner: "root"
        group: "root"
        mode: '0644'
      notify:
        - Restart kubelet
  handlers:
    - name: Restart kubelet
      ansible.builtin.systemd:
        state: restarted
        name: kubelet
