---
- name: Kuma
  hosts: control
  become: true
  vars_files:
    - "env_vars/kuma.yml"
  tasks:
    - name: Install docker-compose
      ansible.builtin.pip:
        name: docker-compose
    - name: Create directory
      ansible.builtin.file:
        path: /opt/kuma
        state: directory
        owner: root
        group: root
        mode: '0644'
    - name: Copy docker-compose.yaml
      ansible.builtin.copy:
        src: kuma/docker-compose.yaml
        dest: /opt/kuma/docker-compose.yaml
        mode: '0644'
        owner: root
        group: root
    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /opt/kuma
        build: false
      register: output
