---
- name: Nginx
  hosts: control
  become: true
  vars_files:
    - "env_vars/nginx.yml"
  pre_tasks:
    - name: Fail if "dns_cloudflare_api_token" is undefined
      ansible.builtin.fail:
        msg: "Bailing out. This play requires 'dns_cloudflare_api_token'"
      when: dns_cloudflare_api_token is undefined

    - name: Install bottle python package
      community.general.snap:
        name:
          - certbot-dns-cloudflare

    - name: Copy DNS CloudFlare API token
      ansible.builtin.template:
        src: "nginx/dns_cloudflare_api_token.ini"
        dest: "{{ creds_path }}"
        owner: root
        group: root
        mode: '0600'

    # - name: Install geoip package
    #   ansible.builtin.apt:
    #     name:
    #       - libnginx-mod-http-geoip
    #       - geoip-database
    #     state: present

    # - name: Create directory GeoIp
    #   ansible.builtin.file:
    #     path: /usr/share/GeoIP
    #     state: directory
    #     owner: root
    #     group: root
    #     mode: '0644'

    # - name: Copy GeoIp
    #   ansible.builtin.copy:
    #     src: nginx/GeoIP.dat
    #     dest: /usr/share/GeoIP/GeoIP.dat
    #     mode: '0644'
    #     owner: root
    #     group: root

    # Configure Nginx upstream repo
    - name: Get Nginx key
      ansible.builtin.get_url:
        url: https://nginx.org/keys/nginx_signing.key
        dest: /etc/apt/keyrings/nginx.asc
        mode: '0644'

    - name: Install Nginx upstream repo
      ansible.builtin.apt_repository:
        # mainline repo
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nginx.asc] http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
        state: present

    - name: Set preference for Nginx upstream repo over distribution repository
      ansible.builtin.copy:
        src: nginx/preferences_apt
        dest: /etc/apt/preferences.d/99nginx
        mode: '0644'
        owner: root
        group: root

  roles:
    - geerlingguy.nginx
    - geerlingguy.certbot

  post_tasks:
    - name: Add option to reload Nginx when renewing certificate
      ansible.builtin.lineinfile:
        dest: /etc/letsencrypt/cli.ini
        state: present
        regexp: '^deploy-hook ='
        line: 'deploy-hook = systemctl reload nginx'

    - name: Copy metrics conf
      ansible.builtin.template:
        src: "nginx/metrics.j2"
        dest: "/etc/nginx/conf.d/metrics.conf"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload nginx

    - name: Copy default host conf
      ansible.builtin.template:
        src: "nginx/default.j2"
        dest: "/etc/nginx/conf.d/0000default.conf"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload nginx

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        state: reloaded
        name: nginx
