---
- name: Base
  hosts: all
  become: true
  vars_files:
    - "env_vars/tailscale.yml"
  pre_tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ tailscale_authkey }}
      when: tailscale_authkey is defined
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_args: "--ssh {{ '--accept-dns=false' if is_dns else '' }}"
