---
- name: Base
  hosts: all
  become: true
  vars_files:
    - "env_vars/tailscale.yml"
  pre_tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ tailscale_authkey }}
      when: tailscale_authkey is defined
    - name: Packet forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
      when: is_exit_node
    - name: Packet forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present
      when: is_exit_node
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_args: "--ssh --timeout=2m0s --stateful-filtering {{ '--advertise-exit-node=true' if is_exit_node else ''}} {{ '--accept-dns=false' if is_dns else '' }}"
