---
- name: Yopass
  hosts: control
  become: true
  vars_files:
    - "env_vars/yopass.yml"
  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: /opt/yopass
        state: directory
        owner: root
        group: root
        mode: '0644'
    - name: Copy docker-compose.yaml
      ansible.builtin.copy:
        src: yopass/docker-compose.yaml
        dest: /opt/yopass/docker-compose.yaml
        mode: '0644'
        owner: root
        group: root
    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: /opt/yopass
        build: never
      register: output
