services:
  stirling-pdf:
    container_name: stirling_pdf
    restart: unless-stopped
    image: frooodle/s-pdf:0.36.0
    ports:
      - '10001:8080'
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB