version: "3.0"

services:
  stirling-pdf:
    image: frooodle/s-pdf:0.28.3
    ports:
      - '10001:8080'
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB