services:
  collector:
    container_name: collector
    restart: unless-stopped
    image: otel/opentelemetry-collector:{{ otel_collector_image_tag }}
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - otel_collector

networks:
  otel_collector:
    external: true
    name: otel-collector
